"""
Copy the pdoc docs' contour background into the rustdoc theme.

The Python (pdoc) and Rust (rustdoc) API docs share one topographic
contour texture. It lives as a base64 SVG data URI in pdoc's
``layout.css``, generated by ``docs/generate_contour_bg.py``. Rather than
keep a hand-copied duplicate in ``docs/rustdoc-header.html``, this script
copies it across, so there is only ever one source of truth::

    generate_contour_bg.py --> layout.css (pdoc) --> rustdoc-header.html

In the rustdoc header, the line to replace is the ``background-image``
declaration directly after the ``CONTOUR-BG`` marker comment. The script
is idempotent: re-running it replaces whatever is there with the current
texture.

Dependencies:
    Standard library only.

Examples:
    Run from ``rust/`` after (re)generating the pdoc contour::

        python docs/sync_rustdoc_contour.py path/to/pdoc/layout.css

    Then rebuild the Rust docs::

        cargo doc --no-deps --open
"""

import argparse
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Default theme location: next to this script, in rust/docs/.
DEFAULT_HEADER = Path(__file__).resolve().parent / "rustdoc-header.html"

# The contour in pdoc's layout.css: the first base64 SVG data URI used as
# a background-image. Captures the full ``url("...")`` value.
_LAYOUT_CONTOUR_RE = re.compile(
    r'background-image:\s*(url\("data:image/svg\+xml;base64,'
    r'[A-Za-z0-9+/=]+"\))'
)

# The slot in rustdoc-header.html: the marker comment, then the
# ``background-image`` declaration whose value gets replaced. The value
# is either a quoted ``url("...")`` or a bare keyword like ``none``; the
# url alternative must come first and consume the whole quoted string,
# because the data URI itself contains a ";" (``svg+xml;base64``).
_HEADER_SLOT_RE = re.compile(
    r"(/\* CONTOUR-BG:[^*]*\*/\s*background-image:\s*)"
    r'(?:url\("[^"]*"\)|[^;]*)'
    r"(;)"
)


# ---------------------------------------------------------------------------
# Extraction and substitution
# ---------------------------------------------------------------------------

def extract_contour(layout_css: str) -> str | None:
    """
    Find the contour background in pdoc's layout.css.

    Args:
        layout_css (str): Full text of pdoc's ``layout.css``.

    Returns:
        str | None: The ``url("data:image/svg+xml;base64,...")`` value,
            or ``None`` if no base64 SVG background-image is present.

    Examples:
        >>> extract_contour('background-image: url("data:image/svg+xml;'
        ...                 'base64,PHN2Zz4=");')
        'url("data:image/svg+xml;base64,PHN2Zz4=")'
    """
    match = _LAYOUT_CONTOUR_RE.search(layout_css)
    return match.group(1) if match else None


def insert_contour(header_html: str, contour_url: str) -> str | None:
    """
    Put a contour background into the rustdoc header's marked slot.

    Args:
        header_html (str): Full text of ``rustdoc-header.html``.
        contour_url (str): The ``url(...)`` value to insert.

    Returns:
        str | None: The updated header text, or ``None`` if the
            ``CONTOUR-BG`` marker and its ``background-image`` line
            weren't found.
    """
    # A replacement function, not a replacement string, so backslashes
    # or group references in the data can never be misinterpreted.
    updated, count = _HEADER_SLOT_RE.subn(
        lambda m: m.group(1) + contour_url + m.group(2),
        header_html,
        count=1,
    )
    return updated if count == 1 else None


# ---------------------------------------------------------------------------
# Command-line entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    """
    Copy the contour from layout.css into rustdoc-header.html.

    Args:
        argv (list[str] | None): Command-line arguments, excluding the
            program name. ``None`` means ``sys.argv[1:]``.

    Returns:
        int: Process exit code: ``0`` on success, ``1`` if either file
            is missing or doesn't contain what's expected.
    """
    parser = argparse.ArgumentParser(
        description="Copy pdoc's contour background into the rustdoc theme.",
    )
    parser.add_argument(
        "layout_css",
        type=Path,
        help="path to pdoc's layout.css",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=DEFAULT_HEADER,
        help=f"rustdoc theme to update (default: {DEFAULT_HEADER})",
    )
    args = parser.parse_args(argv)

    try:
        layout_css = args.layout_css.read_text(encoding="utf-8")
        header_html = args.header.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    contour_url = extract_contour(layout_css)
    if contour_url is None:
        print(
            f"[ERROR] No base64 SVG background-image in {args.layout_css}",
            file=sys.stderr,
        )
        return 1

    updated = insert_contour(header_html, contour_url)
    if updated is None:
        print(
            f"[ERROR] No CONTOUR-BG slot found in {args.header}",
            file=sys.stderr,
        )
        return 1

    if updated == header_html:
        print(f"Already up to date: {args.header}")
        return 0

    args.header.write_text(updated, encoding="utf-8")
    size_kb = len(contour_url) / 1024
    print(f"Updated {args.header} ({size_kb:.1f} KB contour)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
